version: "3"
services:
  php71-first:
    build:
      context: ./images/php74
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - ./www:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1 remote_autostart=off  remote_port=9008"
      PHP_IDE_CONFIG: "serverName=first"
    networks:
      - test-network
  nginx-test:
    image: nginx
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - php71-first
    networks:
      test-network:
        aliases: # алиасы нужны если нужно общаться внутри сети между хостами. Например, если вы используете api
          - first.loc
  mysql-test:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
